name: Update Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code --function-name echoObject --zip-file fileb://lambda.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIA3FLDYRTVQBSG4TOT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.0uYuiUMZdEvDX+8T7cvkY7/ax+fxBH60i+sT6hEr }}
